### ISSUE TITLE
BTLEDisconnectError (maybe not due to the "usual" reason)

### ISSUE THREAD

**Issue by gittehupe** [FaserF/hassio-addons#10]
Hi,

since I was having trouble running two EQ-3 thermostats with eq3btsmart stable on Home Assitant I wanted to give bt-mqtt-gateway a try.

My set-up is as follows:
I am running a RASPBERRY PI 4 MODEL B 4 GB RAM with  "Raspbian GNU/Linux 10 (buster)" from raspberrypi.org.
Home Assistant is running **via docker** in a "Home Assistant Container" as described on [www.home-assistant.io](https://www.home-assistant.io/docs/installation/docker/). With the supervisor I installed this "Home Assistant Community Add-on: Bluetooth-MQTT-Gateway".

Even though eq3btsmart was working at least sporadically (just loosing contact from time to time) I was not able to get _any_ connection with bt-mqtt-gateway. I just get always the following messages:
```
19:32:46 Updating 2 thermostat devices
19:32:46 Error during update of thermostat device 'c3er' (XX:XX:XX:XX:XX:XX): BTLEDisconnectError
19:32:46 Error during update of thermostat device 'c5er' (YY:YY:YY:YY:YY:YY): BTLEDisconnectError
```
The MAC addresses are correctly configured in /config/bt-mqtt-gateway.yaml:
```
mqtt:
  host: 192.168.1.55
  port: 1883
  username: myname
  password: mypassword
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True
  #topic_prefix: hostname         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35           # Timeout for worker operations. Can be removed if the default of 35 seconds is sufficient.
  workers:
    # mysensors:
    #   command_timeout: 35       # Optional override of globally set command_timeout.
    #   args:
    #     port: /dev/ttyUSB0
    #     baudrate: 9600
    #     topic_prefix: mysensors/out
    thermostat:
      args:
        devices:
          c3er: 
            mac: XX:XX:XX:XX:XX:XX  # Simple format
          c5er:                # Extended format with additional configuration
            mac: YY:YY:YY:YY:YY:YY
            discovery_temperature_topic: some/sensor/with/temperature       # Optional current_temperature_topic for HASS discovery
            discovery_temperature_template: "{{ value_json.temperature }}"  # Optional current_temperature_template for HASS discovery
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      update_interval: 30
```

I can connect to the bluetooth devices in the homeassistant container (after entering it with "docker exec -it homeassistant /bin/bash") with bluetoothctl, though. Both EQ-3 thermostats are "paired" and "trusted". I manage to connect to both of them (even though they disconnect pretty soon again which just might be normal?!). So, I would not assume a general bluetooth connection problem.

Now, acccording to my understanding the bt-mqtt-gateway is started in this configuration in a separate docker environment. Might the source of the problem be that Home Assistant itself is already running in a docker environment?

I noticed that running bluetoothctl _in the addon-bt-mqtt-gateway docker environment_ leads only to the following error:
```
Waiting to connect to bluetoothd...dbus[308]: arguments to dbus_connection_get_object_path_data() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 5905.
This is normally a bug in some application using the D-Bus library.

  D-Bus not compiled with backtrace support so unable to print a backtrace
Aborted (core dumped)
```

Unfortunately, I did not manage to run bt-mqtt-gateway in debug mode since its configuration is still ignored. Any hint on how to achieve this?

Apart from that I would be very happy for any tip on how to get it running in the end... 

Thanks a lot in advance!
